///<reference types = "Cypress"/>

describe('Measure PD',function(){
    it ('TC_001', function(){
    cy.visit('https://www.ezcontacts.com')
    cy.wait(2000)
    cy.reload()
    cy.get(':nth-child(4) > .list-unstyled > :nth-child(6) > a').should('contain.text','Measure PD').click()
    cy.wait(2000)
    cy.get('.measure-pd-section > center > .btn').should('contain.text',' Click To Start Our Online PD Tool ').click()
    cy.wait(1000)
    cy.get('.veero-eyefit-h2').should('exist')
    cy.get("div[id='veero-launch-cc-button'] button[type='button']").click()
    cy.wait(1000)
    cy.get('#veero-eyesize-message-text').should('exist')
    cy.wait(3000)
    cy.get('#veero-eyesize-button').click()
    cy.wait(1000)
    cy.get('#veero-eyesize-button').click()
    cy.wait(1000)
    cy.get('#veero-eyesize-button').click()
    cy.wait(1000)
    cy.get('#veero-eyesize-skip-instructions-button').click()
    cy.get('#veero-eyesize-message-text').should('exist')
    // cy.get('.go-title').should('contain.text','Before we start')
    // cy.wait(1000)
    // cy.get('.go-btn').should('contain.text','Show me how').click()
    // cy.wait(6000)
    // cy.get('.go-btn').should('contain.text','Next').click()
    // cy.wait(10000)
    // cy.get('.go-title').should('contain.text','Eyes not detected')
    // cy.get('.go-message > div').should('exist')
    })
})